application: socialyeller
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /android_register
  script: Android_Register.app

- url: /android_login
  script: Android_Login.app

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /font
  static_dir: font

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
